tf_vpn_subnet: 10.0.128.0 255.255.255.0
tf_cwd: /Users/enrico/git/aws-certified-dev/terraform/vpc/public/instances/openvpn/ansible
tf_ca_crt: /usr/local/etc/pki/ca.crt
tf_server_crt: /usr/local/etc/pki/issued/openvpn-server.crt
tf_server_key: /usr/local/etc/pki/private/openvpn-server.key
tf_server_static_key: /usr/local/etc/pki/ta.key
tf_push_routes: ["10.0.0.0 255.255.192.0","10.0.64.0 255.255.192.0"]
tf_dns_server: 10.0.0.2 255.255.192.0
